### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by Bodhi14** [Bodhi14/Patient-API#1]
- [x] Making a gin server with API endpoint to get data
- [x] Making a SQL table that will store the data along with another field named -> is_sms_sent( boolean )
- [ ] Using same handler send text SMS using Text Local
